 x = 5;
 y = 7;
 z = 9;
let promedio = (x + y + z) / 3;
console.log(promedio);
x = -2;
y = -3;
z = -8;
promedio = (x + y + z) / 3;
console.log(promedio);
x = -1.2;
y = 5.3;
z = -3.3;
promedio = (x + y + z) / 3;
console.log(promedio);